// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqgaVyg1jtvKyCJH30eXsSzDCPjb_tSYQ',
    appId: '1:488526922653:web:ccaedbcf1a577a0bf4e574',
    messagingSenderId: '488526922653',
    projectId: 'basebackend-51a59',
    authDomain: 'basebackend-51a59.firebaseapp.com',
    databaseURL: 'https://basebackend-51a59-default-rtdb.firebaseio.com',
    storageBucket: 'basebackend-51a59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP8rx3gIXHEE-O6qZMjhk-FzwUZBb4doc',
    appId: '1:488526922653:android:fa012e8e5b8a3955f4e574',
    messagingSenderId: '488526922653',
    projectId: 'basebackend-51a59',
    databaseURL: 'https://basebackend-51a59-default-rtdb.firebaseio.com',
    storageBucket: 'basebackend-51a59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHwsX__XekK-8-vxWgv17wkOzprmZs8gA',
    appId: '1:488526922653:ios:e1b8826075939e7cf4e574',
    messagingSenderId: '488526922653',
    projectId: 'basebackend-51a59',
    databaseURL: 'https://basebackend-51a59-default-rtdb.firebaseio.com',
    storageBucket: 'basebackend-51a59.appspot.com',
    androidClientId: '488526922653-j7g8nucrn42otc4bhfm706653ejivees.apps.googleusercontent.com',
    iosClientId: '488526922653-pp2ea4oqutelms8m3j0jg2dl3m1be6nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotePharmachem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHwsX__XekK-8-vxWgv17wkOzprmZs8gA',
    appId: '1:488526922653:ios:e1b8826075939e7cf4e574',
    messagingSenderId: '488526922653',
    projectId: 'basebackend-51a59',
    databaseURL: 'https://basebackend-51a59-default-rtdb.firebaseio.com',
    storageBucket: 'basebackend-51a59.appspot.com',
    androidClientId: '488526922653-j7g8nucrn42otc4bhfm706653ejivees.apps.googleusercontent.com',
    iosClientId: '488526922653-pp2ea4oqutelms8m3j0jg2dl3m1be6nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotePharmachem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqgaVyg1jtvKyCJH30eXsSzDCPjb_tSYQ',
    appId: '1:488526922653:web:fd82ff1b8a8d08acf4e574',
    messagingSenderId: '488526922653',
    projectId: 'basebackend-51a59',
    authDomain: 'basebackend-51a59.firebaseapp.com',
    databaseURL: 'https://basebackend-51a59-default-rtdb.firebaseio.com',
    storageBucket: 'basebackend-51a59.appspot.com',
    measurementId: 'G-W4NCHYD3QF',
  );

}